networks:
  net:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    networks:
      - net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
    container_name: 'app-container'
    restart: unless-stopped
    hostname: server
    environment:
      TOKEN_MINUTE_LIFESPAN: 24
      REFRESH_HOUR_LIFESPAN: 48
      API_SECRET: api-secret
      REFRESH_SECRET: refresh-secret
    ports:
      - 7001:7001
    command: ./app
    network_mode: "host"
volumes:
  pg-data:


