// Code generated by mockery v2.46.3. DO NOT EDIT.

package goals_checker

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTimeManager is an autogenerated mock type for the TimeManager type
type MockTimeManager struct {
	mock.Mock
}

// GetCurrentTime provides a mock function with given fields: ctx, username
func (_m *MockTimeManager) GetCurrentTime(ctx context.Context, username string) (time.Time, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTimeManager creates a new instance of MockTimeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimeManager {
	mock := &MockTimeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
