// Code generated by mockery v2.46.3. DO NOT EDIT.

package progress_adder

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

// RunRepeatableRead provides a mock function with given fields: ctx, fx
func (_m *MockTransactor) RunRepeatableRead(ctx context.Context, fx func(context.Context) error) error {
	ret := _m.Called(ctx, fx)

	if len(ret) == 0 {
		panic("no return value specified for RunRepeatableRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
