// Code generated by mockery v2.46.3. DO NOT EDIT.

package habit

import (
	context "context"
	entities "testing_trainer/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// ArchiveHabitById provides a mock function with given fields: ctx, habitId
func (_m *MockStorage) ArchiveHabitById(ctx context.Context, habitId int) error {
	ret := _m.Called(ctx, habitId)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveHabitById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, habitId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateGoal provides a mock function with given fields: ctx, habitID, goal
func (_m *MockStorage) CreateGoal(ctx context.Context, habitID int, goal entities.Goal) (int, error) {
	ret := _m.Called(ctx, habitID, goal)

	if len(ret) == 0 {
		panic("no return value specified for CreateGoal")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, entities.Goal) (int, error)); ok {
		return rf(ctx, habitID, goal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, entities.Goal) int); ok {
		r0 = rf(ctx, habitID, goal)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, entities.Goal) error); ok {
		r1 = rf(ctx, habitID, goal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateHabit provides a mock function with given fields: ctx, username, _a2
func (_m *MockStorage) CreateHabit(ctx context.Context, username string, _a2 entities.Habit) (int, error) {
	ret := _m.Called(ctx, username, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateHabit")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Habit) (int, error)); ok {
		return rf(ctx, username, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Habit) int); ok {
		r0 = rf(ctx, username, _a2)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.Habit) error); ok {
		r1 = rf(ctx, username, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateGoalByID provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeactivateGoalByID(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateGoalByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrentPeriodExecutionCount provides a mock function with given fields: ctx, goal
func (_m *MockStorage) GetCurrentPeriodExecutionCount(ctx context.Context, goal entities.Goal) (int, error) {
	ret := _m.Called(ctx, goal)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentPeriodExecutionCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Goal) (int, error)); ok {
		return rf(ctx, goal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Goal) int); ok {
		r0 = rf(ctx, goal)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Goal) error); ok {
		r1 = rf(ctx, goal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentProgress provides a mock function with given fields: ctx, goalId
func (_m *MockStorage) GetCurrentProgress(ctx context.Context, goalId int) (entities.Progress, error) {
	ret := _m.Called(ctx, goalId)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentProgress")
	}

	var r0 entities.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Progress, error)); ok {
		return rf(ctx, goalId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Progress); ok {
		r0 = rf(ctx, goalId)
	} else {
		r0 = ret.Get(0).(entities.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, goalId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHabitById provides a mock function with given fields: ctx, username, habitId
func (_m *MockStorage) GetHabitById(ctx context.Context, username string, habitId int) (entities.Habit, error) {
	ret := _m.Called(ctx, username, habitId)

	if len(ret) == 0 {
		panic("no return value specified for GetHabitById")
	}

	var r0 entities.Habit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (entities.Habit, error)); ok {
		return rf(ctx, username, habitId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) entities.Habit); ok {
		r0 = rf(ctx, username, habitId)
	} else {
		r0 = ret.Get(0).(entities.Habit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, username, habitId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHabitGoal provides a mock function with given fields: ctx, habitId
func (_m *MockStorage) GetHabitGoal(ctx context.Context, habitId int) (entities.Goal, error) {
	ret := _m.Called(ctx, habitId)

	if len(ret) == 0 {
		panic("no return value specified for GetHabitGoal")
	}

	var r0 entities.Goal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Goal, error)); ok {
		return rf(ctx, habitId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Goal); ok {
		r0 = rf(ctx, habitId)
	} else {
		r0 = ret.Get(0).(entities.Goal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, habitId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserCompletedHabits provides a mock function with given fields: ctx, username
func (_m *MockStorage) ListUserCompletedHabits(ctx context.Context, username string) ([]entities.Habit, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ListUserCompletedHabits")
	}

	var r0 []entities.Habit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Habit, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Habit); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Habit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserHabits provides a mock function with given fields: ctx, username
func (_m *MockStorage) ListUserHabits(ctx context.Context, username string) ([]entities.Habit, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ListUserHabits")
	}

	var r0 []entities.Habit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Habit, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Habit); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Habit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGoalStat provides a mock function with given fields: ctx, goalId, progress
func (_m *MockStorage) UpdateGoalStat(ctx context.Context, goalId int, progress entities.Progress) error {
	ret := _m.Called(ctx, goalId, progress)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGoalStat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, entities.Progress) error); ok {
		r0 = rf(ctx, goalId, progress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateHabit provides a mock function with given fields: ctx, _a1
func (_m *MockStorage) UpdateHabit(ctx context.Context, _a1 entities.Habit) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHabit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Habit) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
